### ISSUE TITLE
helm: Update helm deployment container images to refer to nexus on "main" branch

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-helm#15]
Grab fixes for security-bootstrapper and secretstore-setup and update helm chart with nexus-based images.

See https://github.com/edgexfoundry/edgex-go/issues/3851 and https://github.com/edgexfoundry/edgex-go/issues/3852

Use nexus repository and "latest" image.   (Do this for all EdgeX images)

Also update all 3rd party images to refer to latest docker-compose versions used.   See https://github.com/edgexfoundry/edgex-compose/blob/main/compose-builder/.env

```
    bootstrapper:
      repository: edgexfoundry/security-bootstrapper
      tag: "2.2.0"
      pullPolicy: IfNotPresent
    secretstoresetup:
      repository: edgexfoundry/security-secretstore-setup
      tag: "2.2.0"
      pullPolicy: IfNotPresent
```
